### ISSUE TITLE
Extension request: Login ARL only on server

### ISSUE THREAD

**Issue by AlexanderSch90** [Bockiii/deemix-docker#1]
Thanks for this Docker container! Can you somehow set up that the ARL code is stored on the server side and does not have to be entered by every web client? (Maybe with the config folder?)

**Comment by Bockiii** [comment]
Not really in my hands tbh. The problem is that the deemix repo closed the Issues part on their repo, so you can't request anything.

I'll do this: If they don't put it into their native code, I will look into patching it into the container at a later point.

**Comment by AlexanderSch90** [comment]
Does it make sense to leave the issue open until the feature is implemented :-)?
I have one more question: Apparently they work on "deemix" every day. Are the updates transferred directly to the Docker or do you do it manually and I see it in the Dockerhub?

**Comment by Bockiii** [comment]
I don't want to leave it open as there is no potential todo for me right now. But I wrote with the deemix dev an they have basically already prepared such functionality (the  cli can already read the arl from file). So I would wait a bit. 

On the second question : yes, my container pulls the latest deemix code on startup. So using stop/start will work the same as compose up/down/stop.

**Comment by Bockiii** [comment]
@AlexanderSch90 

Your prayers have been answered. ARL is now available as an environment variable. See the readme on how to use it.
