### ISSUE TITLE
Docker install - getting this error - python3: can't open file '/deemix/server.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dmurphydrtc** [Bockiii/deemix-docker#10]
Getting the following error. Raspbian Buster / rpi4. I had this working last week. docker-compose.yml listed below. Thanks in advance.

[services.d] starting services
./run: line 3: cd: /deemix: No such file or directory
[services.d] Starting with ARL
[services.d] done.
python3: can't open file '/deemix/server.py': [Errno 2] No such file or directory
./run: line 3: cd: /deemix: No such file or directory
[services.d] Starting with ARL
python3: can't open file '/deemix/server.py': [Errno 2] No such file or directory
./run: line 3: cd: /deemix: No such file or directory

➜  deemix-docker git:(master) ✗ cat docker-compose.yml
version: '3.3'
services:
    deemix:
        image: bocki/deemix
        container_name: Deemix
        volumes:
            - /mnt/backup/down_deemix/:/downloads
           # - /home/pi/deemix-docker:/config
            - /your/config/location:/config
        environment:
            - PUID=1000
            - PGID=1000
            - ARL=1234567
        ports:
            - 9666:9666

**Comment by Bockiii** [comment]
Is that your actual docker-compose.yml? Because you still have the placeholders for the Config path and the ARL in there. 

For the issue: It looks like it didn't download the repo. Can you post the complete log output? The downloading part before that would be interesting.

**Comment by justified999** [comment]
Hi I am having the same issue.

This is the error in the logfile :

fatal: unable to access 'https://notabug.org/RemixDev/deemix.git/': Could not resolve host: notabug.org
touch: cannot touch '/deemix/updated': No such file or directory

I am running the docker package on Synology NAS - everything most recent version and I have been able to install and run other Docker images fine.

Any suggestions how to fix?

Thanks

**Comment by Bockiii** [comment]
Looks like notabug is having website issues. The website itself is not working right now, so the container can't pull from it as well.

**Comment by Bockiii** [comment]
I just tried it and it works again. I assume it was a temporary website issue.
