### ISSUE TITLE
404 on url

### ISSUE THREAD

**Issue by tborychowski** [Bockiii/deemix-docker#13]
I followed the setup guide for docker-compose and logs seem to show that it has started but I do get 404 when I try to access the url in the browser.
(old deezer-loader works fine for me)

Not sure if this is important - I run this in a docker on my headless server, so I don't access localhost/127.0.0.1, as the log states:
```
Starting server at http://127.0.0.1:9666
```
but rather `<my server IP>:port`

**Comment by agilly1989** [comment]
> I followed the setup guide for docker-compose and logs seem to show that it has started but I do get 404 when I try to access the url in the browser.
> (old deezer-loader works fine for me)
> 
> Not sure if this is important - I run this in a docker on my headless server, so I don't access localhost/127.0.0.1, as the log states:
> 
> ```
> Starting server at http://127.0.0.1:9666
> ```
> 
> but rather `<my server IP>:port`

After some searching, this was a change in https://notabug.org/RemixDev/deemix-pyweb/src/master/server.py where they changed the server ip from `0.0.0.0` to `127.0.0.1`. A Suggestion to Bockiii is to add an IP enviroment variable that we can set that ourselves

**Comment by nledford** [comment]
@agilly1989's fix worked like a charm for me.

**Comment by FlorianLaunay** [comment]
Another fix is mentioned here : https://www.reddit.com/r/deemix/comments/gx1wxg/help_troubleshooting_err_connection_refused_on/

@Bockiii could you modify the daemon startup command by adding the `--host=0.0.0.0` option mentioned here : https://notabug.org/RemixDev/deemix-pyweb/commit/c403ee720ff2e12a81cbab588d05d264c2881561 ?

**Comment by Bockiii** [comment]
Remixdev changed that ip 10 hours ago. I will fix this as soon as I get home

**Comment by Bockiii** [comment]
Everything is fixed, but you have to move to the new docker container. See readme.
