### ISSUE TITLE
Failed to establish a new connection: [Errno 113] Host is unreachable

### ISSUE THREAD

**Issue by Mbarmem** [Bockiii/deemix-docker#14]
Receiving the following error when i try to download songs:
`HTTPSConnectionPool(host='e-cdns-proxy-0.dzcdn.net', port=443): Max retries exceeded with url: /mobile/1/axxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9afa9c1390>: Failed to establish a new connection: [Errno 113] Host is unreachable',))
`

**Comment by Bockiii** [comment]
Everything is fixed, but you have to get the new docker container. See readme in this repo.
