### ISSUE TITLE
Playlist - save covers

### ISSUE THREAD

**Issue by jabibenito** [Bockiii/deemix-docker#3]
Hi,

When you download any playlist, program does not download the cover. If you download any album it works nice. I have also tried the option "Save playlists as compilation" and in this way it creates the file covert.jpeg but it only takes up a few bytes without information inside.

Would be nice to be able to download the cover of the playlist too.

Regards,
Jabi

**Comment by Bockiii** [comment]
Hi, 

Sorry, but this is not the development github for deemix, this is only for the docker container.

The link to the deemix repo is in the description, but they have closed the issues for now, so either try the subreddit or wait until they open the issues section.

Can't help you here with that request. closed.
