### ISSUE TITLE
Change download path to local machine

### ISSUE THREAD

**Issue by ihatem** [Bockiii/deemix-docker#4]
I'm totally noob with docker, can you tell me how to make the running docker container download files to my physical hard drive because the files are being downloaded to the container (which i've shell and `ls` the downloads directory.

**Comment by RyanRadly** [comment]
When you're running the docker, the -v flags are what map volumes from the container to outside the container, so the line:

-v /your/storage/path/:/downloads

is what maps a local path to /downloads in the container.

**Comment by Bockiii** [comment]
^

his answer.
