### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by appark** [Bockiii/deemix-docker#5]
Is there a way to protect webpage?  Login with password so strangers cant use it?

**Comment by Bockiii** [comment]
Not within the scope of this container. I also can't see a use case for that. Do you have that many strangers in your wifi? 

If you dont use serverwide arl, the stranger would need to log in with his arl, which he will probably not know anyways without research. 

So no.. not in the scope of this container. You could research into using organizr as a proxy or so... no idea.
