### ISSUE TITLE
Image doesnt install dependancies on first run

### ISSUE THREAD

**Issue by KeenJelly** [Bockiii/deemix-docker#6]
I need to install the dependancies

flask
flask_socketio
pycryptodomex
mutagen
spotipy

before it would load.

**Comment by appark** [comment]
yes same result here

**Comment by Bockiii** [comment]
Found the issue. They added a new requirement which needs a new apk package installed. Fixed it, container is building right now and will be available in a few minutes. Just pull the newest image and it will build the app as usual.

Be aware, the new thing they implemented (gevent-websocket) is quite big and needs some time to install. So you will have to wait a bit longer. The log will tell you when it's done.
