### ISSUE TITLE
Webserver-Logs

### ISSUE THREAD

**Issue by AlexanderSch90** [Bockiii/deemix-docker#7]
Can you please help me technically. I use HA proxy to access this server via HTTPS with certificate etc. To do this, the server (deemix) is connected normally via HTTP to HA Proxy. HA proxy keeps spitting out errors in the log when communicating with deemix. Now the log information from deemix would be interesting to find the error ... Where are they saved and can you put them on debug? I need the web server communication. Thank you for a tip.

**Comment by Bockiii** [comment]
Hi, Sorry no idea. I'm not proficient in python so I have no idea where or how to enable logging into a file or changing log levels. You could ask in the subreddit, maybe one of the devs can answer this. Cant help you here though :/
