### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by jonhoffmam** [Bockiii/deemix-docker#8]
I updated to the latest version and when the container is started, an error is returned for not finding the "flask" module!

Any idea what's going on?

**The error log:**
```
[services.d] Starting with ARL
Traceback (most recent call last):,
  File "/deemix/server.py", line 6, in <module>,
    from flask import Flask, render_template, request, session,
ModuleNotFoundError: No module named 'flask'
```
**Note:** The previous version started, but had another problem, which was the reason for the update.

**Comment by Bockiii** [comment]
I just recreated my container and it does not show that issue, so it has to be either something temporary (so just recreate your container and it should work) or something to do with your config.

I would assume the first though. So just recreate your container and it should work.
