### ISSUE TITLE
Today’s download fix

### ISSUE THREAD

**Issue by geekaroni** [Bockiii/deemix-docker#9]
There was a fix today for the download issue. https://www.reddit.com/r/deemix/comments/gmu7lv/fixed_deemix_server_hanging_while_downloading/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Fixed deemix server hanging while downloading tracks

This should fix the tracks in the queue not appearing until they all get downloaded, plus other problems.

Update deemix and run this in the command prompt/terminal:

`python3 -m pip uninstall gevent gevent-websocket`

If you're using the pre-built executable (it's the .zip in the news channel) wait for an updated one.

**Comment by Bockiii** [comment]
Jup. Just rebuild the container and it will be fixed.
